import enterprise from "./enterprise.jpg"
import ahmedabad from "./jhultaminar-125654.svg"
import chennai from "./chennai-125658.svg"
import rajasthan from "./hawamahal-125657.svg"
import delhi from "./gatewayofindia-125649.svg"
import hyderabad from "./charminar-125651.svg"
import kerela from "./kerala-125650.svg"
import truck from "./Truck.svg"
import BetterEearning from "./BetterEarning.png"
import  regularTrip from "./regularTrip.png"
import Delivery from "./delivery.jpg";
import onTImePayment from "./onTImePayment.png"; 
import driverExperience from "./driver_experience.gif";
import profilePic from "./profile_pic.png";
import ownVehicles from "./own_vehicles.png";
export {Delivery,regularTrip,BetterEearning, onTImePayment, driverExperience,enterprise,ahmedabad,chennai,rajasthan,delhi,kerela,hyderabad,profilePic,ownVehicles}